.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. reptiloidscoin_qt test_reptiloidscoin_qt
clean: FORCE
	$(MAKE) -C .. reptiloidscoin_qt_clean test_reptiloidscoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_reptiloidscoin_qt_check
reptiloidscoin-qt reptiloidscoin-qt.exe: FORCE
	 $(MAKE) -C .. reptiloidscoin_qt
